### ISSUE TITLE
A hyperlinked Table of Content can be included which would improve accessibility and readability of repo.

### ISSUE THREAD

**Issue by nickson-jose** [prajwalita17/Advanced-Physical-Design-using-OpenLANE-and-Skywater-130-PDK#1]
A hyperlinked Table of Content can be included which would improve accessibility and readability of repo.

**Comment by prajwalita17** [comment]
Thanks for the feedback. I included the indexed table of content in the repo.

**Comment by nickson-jose** [comment]
Great!
